# This is a basic workflow to help you get started with Actions

name: Create Pull Request for new React components

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ newReactFiles ]
    
jobs:
  create-pr-on-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@1.0.0
    
    - name: Create pull request
      uses: thomaseizinger/create-pull-request@master
      with:
        GITHUB_TOKEN: ${{ secrets.PR_TOKEN }}
        branch: newReactFiles
        head: "master"
        title: "An automatically created PR!"
